### ISSUE TITLE
Want to add sciruby?

### ISSUE THREAD

**Issue by minad** [rubygsoc/rubygsoc#1]
https://github.com/SciRuby/sciruby/wiki/Google-Summer-of-Code-2014-Ideas

**Comment by tarcieri** [comment]
We can just for completeness, however SciRuby is applying (and has traditionally been accepted as) a toplevel GSoC mentoring organization.

The `rubygsoc` project is attempting to revive the overall Ruby GSoC organization. All of the projects under our ideas list are potential ones for Ruby GSoC, which we want to do independently of SciRuby.

If SciRuby isn't accepted as a mentoring organization but Ruby is, that's a completely different story, of course!

**Comment by agarie** [comment]
Actually, last year was the first time SciRuby was accepted in GSoC. :)

I hope rubygsoc gets accepted as well!

**Comment by minad** [comment]
Sure, I don't know much about the formal backgrounds. I just thought that this could be of interest if you are collecting ideas/projects which want to participate in gsoc. Maybe just add a link?

**Comment by tarcieri** [comment]
At this point we're just trying to apply to Google as a mentoring organization. If we're accepted we can spend some more time building out resources.
